cmake_minimum_required(VERSION 4.0) #создали минимальный CMake
project(lab0a-main) #Указали цель (название проекта), Регистрирует имя всего проекта в системе.

add_subdirectory(src/module1) # Указали путь до библиотеки, которую надо подключить.0Говорит CMake заглянуть в указанную папку, найти там внутренний файл CMakeLists.txt и выполнить его. Именно в этот момент собирается наша статическая библиотека module1.

add_executable(
        lab0a-main
        main.cpp
        src/module2/module2.cpp
        src/module2/module2.h
) #Создает главную цель (target) проекта — исполняемый файл (программу) с именем lab0a-main (в Windows это будет lab0a-main.exe).Как работает: Внутрь скобок мы перечисляем все файлы исходного кода, которые компилятор должен превратить в эту программу: main.cpp, а также файлы второго модуля src/module2/module2.cpp и src/module2/module2.h.


target_include_directories(lab0a-main PRIVATE src/module2) #Указывает компилятору, где искать заголовочные файлы для сборки программы lab0a-main.Почему PRIVATE: Потому что lab0a-main — это конечный исполняемый файл (наша готовая программа). Выше нее по цепочке никого нет, её никто больше к себе подключать не будет. Соответственно, путь к папке src/module2 нужен только ей самой для компиляции main.cpp.
target_compile_features(lab0a-main PRIVATE cxx_std_20) #требования фич и настроек для С++20
target_link_libraries(lab0a-main PRIVATE module1)#Эта команда производит линковку (связывание). Она берет скомпилированную статическую библиотеку первого модуля и «вшивает» ее код в готовую программу lab0a-main.