add_library(module1 STATIC module1.cpp module1.h) #Создает статическую библиотеку с именем module1. CMake скомпилирует module1.cpp и объединит его с заголовочным файлом module1.h.

target_compile_features(module1 PRIVATE cxx_std_20) #Указывает, что для компиляции библиотеки module1 требуется стандарт C++20. Модификатор PRIVATE означает, что это требование нужно только самому модулю, а не тем, кто его подключает.

target_include_directories(module1 PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}) #Показывает где сборщику искать заголовочные файлы для цели module1. CMAKE_CURRENT_SOURCE_DIR - подставляет имя текущей дериктории.  Public чтоюы не только сам модуль знал путь до module1.h, но и чтобы при вызове из главного CMakeList  подставлялся нужный путь

# Объявили название будущей библиотеки (цели) - Module1, показали, что она статическая и написали какие файлы понадобятся для сборки
# Указали, что требуются настройни и фичи для С++20
# Указали директорию, где искать заголовосный файл для сборки цели (в текущей), и показали, что этот путь публичный, чтобы более главный CMakeList мог обратиться к полному пути, чтобы не указывать в #include ".....src/Module1.h" полный путь